[0m18:56:03.490916 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8ab506c790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8ab360fd30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8ab360ffd0>]}


============================== 18:56:03.496860 | 532a63d4-b3f0-477a-8f94-e1e0d1171c9e ==============================
[0m18:56:03.496860 [info ] [MainThread]: Running with dbt=1.8.9
[0m18:56:03.498061 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m18:56:03.507313 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object.. Dictionary: {'dir': PosixPath('/home/vscode/.dbt')}
[0m18:56:03.507779 [info ] [MainThread]: Creating dbt configuration folder at 
[0m18:56:58.683192 [debug] [MainThread]: Starter project path: /home/vscode/.local/lib/python3.10/site-packages/dbt/include/starter_project
[0m18:56:58.688455 [info ] [MainThread]: 
Your new dbt project "demo_dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:56:58.689390 [info ] [MainThread]: Setting up your profile.
[0m18:58:25.367914 [error] [MainThread]: Encountered an error:
list index out of range
[0m18:58:25.369272 [error] [MainThread]: Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/dbt/cli/requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/dbt/cli/requires.py", line 101, in wrapper
    return func(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/dbt/cli/main.py", line 470, in init
    results = task.run()
  File "/home/vscode/.local/lib/python3.10/site-packages/dbt/task/init.py", line 347, in run
    self.setup_profile(profile_name)
  File "/home/vscode/.local/lib/python3.10/site-packages/dbt/task/init.py", line 262, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "/home/vscode/.local/lib/python3.10/site-packages/dbt/task/init.py", line 244, in ask_for_adapter_choice
    return available_adapters[numeric_choice - 1]
IndexError: list index out of range

[0m18:58:25.371052 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 141.9283, "process_in_blocks": "416", "process_kernel_time": 0.135953, "process_mem_max_rss": "86180", "process_out_blocks": "80", "process_user_time": 1.151561}
[0m18:58:25.371895 [debug] [MainThread]: Command `dbt init` failed at 18:58:25.371751 after 141.93 seconds
[0m18:58:25.372405 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8ab506c790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8ab360fd30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8ab360f550>]}
[0m18:58:25.372900 [debug] [MainThread]: Flushing usage events
[0m19:26:07.296676 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e52aa14730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e528fd3d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e528fd3d90>]}


============================== 19:26:07.300900 | c8c8f341-9242-4c16-ae9f-3c50b0b3795f ==============================
[0m19:26:07.300900 [info ] [MainThread]: Running with dbt=1.8.9
[0m19:26:07.301613 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt test', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:26:07.302155 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-waynetaketwo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:26:07.303453 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.06611618, "process_in_blocks": "61352", "process_kernel_time": 0.286527, "process_mem_max_rss": "85424", "process_out_blocks": "8", "process_user_time": 1.161191}
[0m19:26:07.304132 [debug] [MainThread]: Command `dbt test` failed at 19:26:07.304025 after 0.07 seconds
[0m19:26:07.304549 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e52aa14730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e528fd3d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e528fd36d0>]}
[0m19:26:07.304995 [debug] [MainThread]: Flushing usage events
